# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 817f232dbb6139f19abff4c4fbfd34589b5c686ef6d93620395967180626d11be8966dc8ba177e5ac99274b4171f7cca1be28555ee29c3210e515003edd816a4

test:
  secret_key_base: fc42a7b7b8793f9eac7ea528767461725c7faf99fc3c2c03e3307f24914c90065120b4751d18b1a81658d1e7f4409b9151db927c5e37189f3ab861a01aaf6319

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
